# Generated by Django 4.2.7 on 2024-11-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=250)),
                ("category", models.CharField(max_length=30)),
                ("difficulty", models.CharField(max_length=10)),
                ("points", models.FloatField()),
                ("optString", models.CharField(max_length=350)),
                ("correctOption", models.IntegerField()),
            ],
        ),
    ]
