# Generated by Django 4.2.7 on 2024-11-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="points",
            field=models.IntegerField(),
        ),
    ]
