# Generated by Django 4.2.7 on 2024-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApi", "0002_alter_question_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=250)),
                ("category", models.CharField(max_length=30)),
                ("difficulty", models.CharField(max_length=10)),
                ("optString", models.CharField(max_length=350)),
                ("correctOption", models.IntegerField()),
            ],
        )
    ]
