# Generated by Django 4.2.7 on 2024-11-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizApi", "0003_pregunta"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Question",
        ),
    ]
